field: 0f4caa01-e20b-4dff-ab17-5f3dcc420286 # Media Cluster
fieldLayouts:
  34bf9947-e6db-4cee-b045-84a892685d87:
    tabs:
      -
        elements:
          -
            fieldUid: 7f995e9d-4ca2-4ca2-aa2f-130fb2015177 # Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c226b8bf-4710-4f15-830b-5dc0d02bc687 # clusterTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7f995e9d-4ca2-4ca2-aa2f-130fb2015177: # Logo
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: ''
    name: Logo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:b5448d96-4178-4e92-bdc8-5e841c0bf592' # Testimonial Images Volume
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c226b8bf-4710-4f15-830b-5dc0d02bc687: # clusterTitle
    contentColumnType: text
    fieldGroup: null
    handle: clustertitle
    instructions: ''
    name: clusterTitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cluster
name: Cluster
sortOrder: 1
