field: d6163fd8-ef19-4bf8-a36a-cc2c73248013 # Services List
fieldLayouts:
  b365241e-d3ea-443b-91a9-000060f4abbc:
    tabs:
      -
        elements:
          -
            fieldUid: c153d41d-5215-4d04-b2d3-439484cfd4ed # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7df4c85-f678-4841-a6c3-ecab30be6b10 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7013ec57-d2d6-490b-b774-0315ffe7dc4a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 91cdc80c-e154-427d-9cfd-a92882519970 # Link Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bd89aea-8187-43c4-af6c-dfd49b2347a4 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a27a6982-eedc-4b9c-86c2-fce4430146e0 # Link Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1bd89aea-8187-43c4-af6c-dfd49b2347a4: # Link Text
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: 'Default: "Learn More"'
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7013ec57-d2d6-490b-b774-0315ffe7dc4a: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  91cdc80c-e154-427d-9cfd-a92882519970: # Link Entry
    contentColumnType: string
    fieldGroup: null
    handle: linkEntry
    instructions: ''
    name: 'Link Entry'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a27a6982-eedc-4b9c-86c2-fce4430146e0: # Link Position
    contentColumnType: string
    fieldGroup: null
    handle: linkPosition
    instructions: ''
    name: 'Link Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Under Text'
            -
              - value
              - underText
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Side
            -
              - value
              - side
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  a7df4c85-f678-4841-a6c3-ecab30be6b10: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c153d41d-5215-4d04-b2d3-439484cfd4ed: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: item
sortOrder: 1
