field: f7987938-6708-4662-8c8d-9bbfe50aa361 # CTA Twin Items
fieldLayouts:
  74628168-f3f2-4b97-867d-d6e3415727c7:
    tabs:
      -
        elements:
          -
            fieldUid: c28fea00-7b97-46fe-9a80-796c2512bf80 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0c2f439-da0d-4f46-9c1e-e7ec1097414a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8643e1ed-6701-4e66-b00d-f37059404f66 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9a1f6c77-330f-4116-b90b-4dc21b9b7cd5 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2929f2df-be8f-4624-b2f3-91482b8effc0 # Link Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75d11f88-9e7e-4105-9d01-690fc1ae137a # Link Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd8cf4ab-bc1d-456c-b24c-60f8ef7ffb13 # Link Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2929f2df-be8f-4624-b2f3-91482b8effc0: # Link Entry
    contentColumnType: string
    fieldGroup: null
    handle: linkEntry
    instructions: ''
    name: 'Link Entry'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  75d11f88-9e7e-4105-9d01-690fc1ae137a: # Link Asset
    contentColumnType: string
    fieldGroup: null
    handle: linkAsset
    instructions: ''
    name: 'Link Asset'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8643e1ed-6701-4e66-b00d-f37059404f66: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9a1f6c77-330f-4116-b90b-4dc21b9b7cd5: # Button Text
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c28fea00-7b97-46fe-9a80-796c2512bf80: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd8cf4ab-bc1d-456c-b24c-60f8ef7ffb13: # Link Type
    contentColumnType: string
    fieldGroup: null
    handle: linkType
    instructions: ''
    name: 'Link Type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Entry
            -
              - value
              - entry
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Asset
            -
              - value
              - asset
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  f0c2f439-da0d-4f46-9c1e-e7ec1097414a: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: items
name: Items
sortOrder: 1
