field: 04691326-dfb1-4320-920d-19a78b16c612 # VREF Print Pricing Items
fieldLayouts:
  c7679e6e-8cb3-48ed-92ed-8b0240551dc2:
    tabs:
      -
        elements:
          -
            fieldUid: 8138facc-3995-4a2a-8a91-5f47dcacaabd # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2ec3204-23cc-4953-a7f1-1dafff2941f8 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd8d9df1-917c-46be-873d-404628bec7be # API Plan ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8138facc-3995-4a2a-8a91-5f47dcacaabd: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a2ec3204-23cc-4953-a7f1-1dafff2941f8: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd8d9df1-917c-46be-873d-404628bec7be: # API Plan ID
    contentColumnType: integer(10)
    fieldGroup: null
    handle: apiPlanId
    instructions: ''
    name: 'API Plan ID'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: item
name: Item
sortOrder: 1
