field: d3d0d635-a856-430f-8c74-1817c1db62f2 # Links
fieldLayouts:
  6864ad23-5475-4456-aeb4-ca332675beb8:
    tabs:
      -
        elements:
          -
            fieldUid: 083dcbb0-2ad4-4200-8a72-26bf8a6bd912 # Link Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5b78d626-0ede-4ba4-8109-e8561aa60d06 # Link Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  083dcbb0-2ad4-4200-8a72-26bf8a6bd912: # Link Title
    contentColumnType: text
    fieldGroup: null
    handle: linkTitle
    instructions: ''
    name: 'Link Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5b78d626-0ede-4ba4-8109-e8561aa60d06: # Link Destination
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkDestination
    instructions: 'URL e.g. linkedin.com, example@email.com'
    name: 'Link Destination'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: linkWrapper
name: 'Include Link'
sortOrder: 1
