field: aa7d232f-992f-4204-8784-c0b71642e11a # Testimonial Items
fieldLayouts:
  94122510-78f9-4ddf-8bf3-1d053d3e8a26:
    tabs:
      -
        elements:
          -
            fieldUid: 3461fc24-5459-4353-83d0-f4a8b68169a7 # Testimonial Header
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86d20760-bf12-49c7-9779-bc55621c609b # Testimonial Excerpt
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3461fc24-5459-4353-83d0-f4a8b68169a7: # Testimonial Header
    contentColumnType: text
    fieldGroup: null
    handle: testimonialHeader
    instructions: ''
    name: 'Testimonial Header'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Testimonial Header'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  86d20760-bf12-49c7-9779-bc55621c609b: # Testimonial Excerpt
    contentColumnType: text
    fieldGroup: null
    handle: testimonialExcerpt
    instructions: 'If the excerpt is longer than 89 characters, end with an ellipses.'
    name: 'Testimonial Excerpt'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testimonial
name: Testimonial
sortOrder: 1
