field: d0701fb7-ccbe-4b03-b118-9500745c89d7 # Page Content Builder
fieldLayouts:
  b879690f-4c96-48bf-92fa-8cc97d979c61:
    tabs:
      -
        elements:
          -
            fieldUid: 4b3939c8-3262-46c2-a0e5-9b8b5b39170e # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: c736c487-dba8-4b5e-8af2-af89336f3c0f # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4b3939c8-3262-46c2-a0e5-9b8b5b39170e: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      assetsFilesSource: 'folder:1'
      assetsFilesSubPath: ''
      assetsImagesSource: 'folder:1'
      assetsImagesSubPath: ''
      editorConfig: Common.json
    translationKeyFormat: null
    translationMethod: none
    type: froala\craftfroalawysiwyg\Field
  c736c487-dba8-4b5e-8af2-af89336f3c0f: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: textAndImage
name: 'Text + Image'
sortOrder: 2
