fieldLayouts:
  aff3d5ce-ad66-4a8f-bfa5-62ca90cb8a54:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: c95ed69a-7b39-448f-8a34-205bb9e8f1f2 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 426a5015-55d3-434d-bfcc-d7a2d4da4c03 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: d6163fd8-ef19-4bf8-a36a-cc2c73248013 # Services List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 985d1d96-c5a4-4d4f-a269-36cd1b0c51e3 # Pricing Calculator Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98edc9fe-c294-4f6c-bbc9-6322f7f1937c # Pricing Calculator Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcb8878f-5469-41b6-940a-71259b048019 # Pricing Calculator Addon Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e5addfb5-a96e-4a54-af70-46d181e61d32 # Pricing Calculator Addon Short Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac842835-838a-412a-9102-aff20c347ae0 # Pricing Calculator Addon Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f4b16cd9-8f3b-4df0-ac6f-6e788fd78b59 # Pricing Calculator Addon Warning
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 9efa906d-1a3e-4158-aa40-095ce2e47ae1 # VREF Online Pricing Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8d6324f-0d51-419d-8748-9dd2bdb354ee # VREF Online Pricing Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1af5009-c957-40ca-a4a0-e0df66751fe8 # VREF Online Pricing Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'VREF Online'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 5bc9461a-5669-490e-a641-356563a6cb29 # VREF Print Pricing Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41f5233c-58c3-455b-8931-23a080cc06bc # VREF Print Pricing Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04691326-dfb1-4320-920d-19a78b16c612 # VREF Print Pricing Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'VREF Print'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 164e8081-ebeb-4c6c-9a0a-922328b8073a # Certificates Pricing Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f34c1284-829f-4b21-87cd-84a289c8f4fc # Certificates Pricing Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc634f9f-b74c-465a-859c-6b0754141a97 # Certificates Pricing Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Certificates
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 8c606104-3bda-4aca-8d8a-0df389eda91a # Consulting Pricing Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Consulting
        sortOrder: 5
handle: pricing
hasTitleField: true
name: Pricing
section: 69ee859a-46c9-4a05-a983-4095278e4d71 # Pricing
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
