handle: footerLinks
instructions: ''
maxNodes: ''
name: 'Footer Links'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6: null # VREF Aircraft Values & Appraisals
sortOrder: 3
structure:
  maxLevels: '2'
  uid: c8537fc0-3626-4b0a-a489-e5d6f1e246c8
