handle: headerLinks
instructions: null
maxNodes: null
name: 'Header Links'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
sortOrder: 30
structure:
  maxLevels: null
  uid: a5842aa8-2ab5-4f47-9b87-7454fbe7c890
