contentColumnType: string
fieldGroup: 73b6d2ea-435b-418f-93b9-a529b2acf34a # Team Elements
handle: activeLinks
instructions: ''
name: Links
searchable: false
settings:
  contentTable: '{{%matrixcontent_activelinks}}'
  maxBlocks: ''
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
