contentColumnType: text
fieldGroup: 773b0290-b28c-4789-ad92-1a0cec81a9e8 # Compare Section
handle: compareTable
instructions: ''
name: 'Compare Table'
searchable: false
settings:
  columnsAddRowLabel: 'Add column'
  columnsInstructions: ''
  columnsLabel: Columns
  rowsAddRowLabel: 'Add row'
  rowsInstructions: ''
  rowsLabel: Rows
translationKeyFormat: null
translationMethod: none
type: supercool\tablemaker\fields\TableMakerField
