contentColumnType: text
fieldGroup: 773b0290-b28c-4789-ad92-1a0cec81a9e8 # Compare Section
handle: compareTitle
instructions: ''
name: 'Compare Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
