contentColumnType: string
fieldGroup: 0d09437d-cc22-40d2-a504-89155a0b4a52 # CTA Section
handle: ctaBackgroundImage
instructions: ''
name: 'CTA Background Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318' # Client Images Volume
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:31fbbb8a-02b3-4d18-ba5f-1046106a8e7c' # Solution Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
