contentColumnType: text
fieldGroup: 0d09437d-cc22-40d2-a504-89155a0b4a52 # CTA Section
handle: ctaTitle
instructions: ''
name: 'CTA Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
