contentColumnType: text
fieldGroup: 22bde7f8-0058-4dda-bf71-059c837a03ef # Digits Section
handle: digitsTitle
instructions: ''
name: 'Digits Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
