contentColumnType: string
fieldGroup: 9171831a-6cf7-45f1-8b5a-8c51c079c22c # Base
handle: footerInfo
instructions: ''
name: 'Footer Info'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footerinfo}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
