contentColumnType: string
fieldGroup: dcc71ec4-79e4-4b6a-a941-31c6a78a39c3 # Dynamic Pages
handle: headerImage
instructions: 'Banner image displayed behind the title.'
name: 'Header Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:fb6e2638-c6df-4a24-8de9-422128e80318'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:898c39e0-9724-4a3b-9ea4-fc1f44479824' # Header Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
