contentColumnType: text
fieldGroup: e9e3bf35-7f73-4c12-8fef-f60ecb59a31b # Hero Section
handle: heroText
instructions: ''
name: 'Hero Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '6'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
