contentColumnType: string
fieldGroup: e9e3bf35-7f73-4c12-8fef-f60ecb59a31b # Hero Section
handle: heroButtonLink
instructions: ''
name: 'Hero Button Link'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
