contentColumnType: text
fieldGroup: 2a89f2c1-ef93-4f7a-8938-bce5a60aadb9 # Solutions
handle: heroText
instructions: ''
name: 'Hero Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '6'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
