contentColumnType: string
fieldGroup: abcbfaff-d169-40db-84ba-c682d3ab6b26 # Logos Section
handle: logosItems
instructions: ''
name: 'Logos Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_logositems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
