contentColumnType: text
fieldGroup: abcbfaff-d169-40db-84ba-c682d3ab6b26 # Logos Section
handle: logosTitle
instructions: ''
name: 'Logos Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
