contentColumnType: text
fieldGroup: 167ecf9b-703f-4c32-871a-46c542514e4b # Media Outlets Section
handle: mediaOutletsTitle
instructions: ''
name: 'Media Outlets Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
