contentColumnType: text
fieldGroup: 73b6d2ea-435b-418f-93b9-a529b2acf34a # Team Elements
handle: personDesignation
instructions: 'e.g. CEO,  Security Advisor'
name: Designation
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
