contentColumnType: text
fieldGroup: 3579ed8a-9b5f-4725-8f35-a8bdae7f0ab4 # Press Room
handle: pressRoomFormTitle
instructions: ''
name: 'Press Room Form Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
