contentColumnType: string
fieldGroup: 0c655ee1-cc7d-4997-ab8f-e34ed61a1378 # Reports Section
handle: reportsItems
instructions: ''
name: 'Reports Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_reportsitems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
