contentColumnType: text
fieldGroup: 0c655ee1-cc7d-4997-ab8f-e34ed61a1378 # Reports Section
handle: reportsText
instructions: ''
name: 'Reports Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
