contentColumnType: string
fieldGroup: c40cadd9-71f4-4224-99a3-744af62e0e46 # Services Section
handle: servicesList
instructions: ''
name: 'Services List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_serviceslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
