contentColumnType: string
fieldGroup: 2a89f2c1-ef93-4f7a-8938-bce5a60aadb9 # Solutions
handle: servicesList
instructions: ''
name: 'Services List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_serviceslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
