contentColumnType: text
fieldGroup: 46e448df-6903-4848-a6c6-3d86e6b042e0 # Products
handle: subtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
