contentColumnType: text
fieldGroup: 686836de-a41f-410b-8fd4-d41fbda79814 # Who We Are
handle: teamMembersText
instructions: ''
name: 'Team Members Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
