contentColumnType: text
fieldGroup: 98143e5f-d155-4853-a6ec-d1e45efca632 # Testimonials Section
handle: testimonialTitle
instructions: ''
name: 'Testimonial Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
