contentColumnType: string
fieldGroup: 98143e5f-d155-4853-a6ec-d1e45efca632 # Testimonials Section
handle: testimonialItems
instructions: ''
name: 'Testimonial Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_testimonialitems}}'
  maxBlocks: ''
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
