contentColumnType: text
fieldGroup: b0fd34ef-c714-42db-8998-e629f96a61b2 # Pricing
handle: vrefOnlinePricingTitle
instructions: ''
name: 'VREF Online Pricing Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
