dateModified: 1656338275
email:
  fromEmail: andrew@andrewlynn.co
  fromName: vref.com
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  blitz:
    edition: standard
    enabled: true
    licenseKey: VC19XLL0ENUQN24MZFFGZDVS
    schemaVersion: 3.6.6
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageType: putyourlightson\blitz\drivers\storage\YiiCacheStorage
      cacheWarmerSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheWarmerType: putyourlightson\blitz\drivers\warmers\GuzzleWarmer
      cachingEnabled: ''
      clearCacheAutomatically: '1'
      customSiteUris: ''
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      excludedQueryStringParams:
        - gclid
        - fbclid
      excludedUriPatterns: ''
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - '.*'
        -
          __assoc__:
            -
              - uriPattern
              - ''
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      mutexTimeout: 1
      outputComments: true
      queryStringCaching: '0'
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      sendPoweredByHeader: true
      warmCacheAutomatically: '1'
  cloner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  entry-count:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.3.0
  fetch:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  froala-editor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: 03YI91WUF04I743HRJNUKATB
    schemaVersion: 3.0.0
  inlinesvg:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  jsonclient:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  kint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mailchimp-subscribe:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  migrationassistant:
    edition: standard
    enabled: true
    licenseKey: JWYTOAPHD85B7ZABO64F4PG8
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: U78Z7KCGSMI4B04OW1M10GO2
    schemaVersion: 1.0.21
  neo:
    edition: standard
    enabled: true
    licenseKey: Q5WJRQ9PFGLK71XIZTDGRKFL
    schemaVersion: 2.9.11
  pagination:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redirect:
    edition: standard
    enabled: true
  schema:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  scss:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: 'The largest aircraft appraisal company in the world with a staff of Senior Accredited aircraft appraisers specializing in all aircraft models and categories. VREF Appraisers Determine the current fair market value and forecasted residual value on all aircraft makes, parts, equipment & more.'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' | {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  simple-sharing:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  turbo:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cacheVersion: 1
      durationInMinutes: '2'
      enabled: ''
system:
  edition: pro
  live: true
  name: vref.com
  retryDuration: null
  schemaVersion: 3.6.6
  timeZone: America/Chicago
