enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6: # VREF Aircraft Values & Appraisals
    enabledByDefault: true
    hasUrls: true
    template: faq
    uriFormat: faq
type: single
