enableVersioning: true
handle: footer
name: Footer
propagationMethod: all
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6: # VREF Aircraft Values & Appraisals
    enabledByDefault: true
    hasUrls: true
    template: partials/_footer
    uriFormat: footer
type: single
