enableVersioning: true
handle: lendersAndInsurers
name: 'Lenders and Insurers'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6: # VREF Aircraft Values & Appraisals
    enabledByDefault: true
    hasUrls: true
    template: solutions/_entry
    uriFormat: 'lenders-and-insurers/{slug}'
type: channel
