enableVersioning: true
handle: newsArticles
name: 'News Articles'
propagationMethod: all
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6:
    enabledByDefault: true
    hasUrls: true
    template: article
    uriFormat: 'news/{slug}'
structure:
  maxLevels: null
  uid: 197de7a1-d7b8-42df-afe6-1a6b34009228
type: structure
