enableVersioning: true
handle: pressRoom
name: 'Press Room'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d66119ad-8f5f-41e8-8169-49f2c51c36b6: # VREF Aircraft Values & Appraisals
    enabledByDefault: true
    hasUrls: true
    template: press_room
    uriFormat: press-room
type: single
